# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 11:15
from __future__ import unicode_literals

import uuid
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    """Channels initial migration."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False)),
                ('reference', models.CharField(
                    max_length=100, unique=True, verbose_name='Reference')),
                ('name', models.CharField(
                    max_length=256, verbose_name='Name')),
                ('lft', models.PositiveIntegerField(
                    db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(
                    db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(
                    db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(
                    db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Category',
                'ordering': ['channel', 'reference'],
                'verbose_name_plural': 'Categories',
            }, ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False)),
                ('reference', models.CharField(
                    max_length=100, unique=True, verbose_name='Reference')),
                ('name', models.CharField(
                    max_length=256, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Channel',
                'ordering': ['reference'],
                'verbose_name_plural': 'Channels',
            }, ),
        migrations.AddField(
            model_name='category',
            name='channel',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='categories',
                to='channels.Channel',
                verbose_name='Channel'), ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='channels.Category'), ),
    ]
