# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    """This migrations adds 'created_at' and 'updated_at' fields. Also, it
    changes 'reference' field to slug."""

    dependencies = [('channels', '0001_initial'), ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='Created At'),
            preserve_default=False, ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Updated At'), ),
        migrations.AddField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='Created At'),
            preserve_default=False, ),
        migrations.AddField(
            model_name='channel',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Updated At'), ),
        migrations.AlterField(
            model_name='category',
            name='reference',
            field=models.SlugField(
                max_length=100, unique=True, verbose_name='Reference'), ),
        migrations.AlterField(
            model_name='channel',
            name='reference',
            field=models.SlugField(
                max_length=100, unique=True, verbose_name='Reference'), ),
    ]
